theme: jekyll-theme-hacker
markdown: kramdown
highlighter: rouge
pygments: true

# Site name (head)
name: PhpTabs Documentation

# Site description (head)
description: Parse and write GuitarPro and MIDI files

# Github repositories and download URLs
github_repository_url: https://github.com/stdtabs/phptabs
github_author_url: https://github.com/landrok
github_author_name: landrok

